version: '3'
services:
    db:
        image: postgres
        ports:
            - "8001:5432"
        environment:
            POSTGRES_USER: "EnoraB"
            POSTGRES_PASSWORD: "secret"
            POSGRES_DB: "nameCloud"
            
    adminer:
        image: "adminer:latest"
        ports:
            - "4444:8000"
            
            